---
# tasks file for easy-pgbouncer
- name: Install PgBouncer on Operating System for RPM
  yum:
    name: pgbouncer
    state: present
  when: >-
    ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat
    Enterprise Linux'

- name: Install PgBouncer on Operating System for DEB
  apt:
    name: pgbouncer
    state: present
    update_cache: "yes"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Grant Permissions to pgbouncer directory for postgresql user
  file:
    path: /etc/pgbouncer/
    owner: postgres
    group: postgres
    mode: '0700'

- name: Grant Permissions to pgbouncer pid directory for postgresql user
  file:
    path: /var/run/pgbouncer/
    owner: postgres
    group: postgres
    mode: '0700'

- name: Grant Permissions to pgbouncer log directory for postgresql user
  file:
    path: /var/log/pgbouncer/
    owner: postgres
    group: postgres
    mode: '0700'

- name: Copy pgbouncer Service File with root Permission(0644)
  copy:
    src: files/pgbouncer.service
    dest: /usr/lib/systemd/system/pgbouncer.service
    owner: root
    group: root
    mode: '0644'

- name: Copy pgbouncer Configuration File with postgres Permission(0644)
  template:
    src: files/pgbouncer.j2
    dest: /etc/pgbouncer/pgbouncer.ini
    owner: postgres
    group: postgres
    mode: '0644'

- name: Start pgbouncer Service on Operating System
  service:
    name: pgbouncer
    state: started
    enabled: 'yes'
